"""empty message

Revision ID: 7afd54ebfdf0
Revises: 
Create Date: 2024-03-13 17:56:12.955806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afd54ebfdf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_model')
    op.drop_table('store_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('storename', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storename')
    )
    op.create_table('item_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_price', sa.FLOAT(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=60), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['StoreTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
